<script lang="ts">
  import { getActions } from "$lib/db/actions";
  import VirtualScroll from "svelte-virtual-scroll-list";

  let actions = getActions();
</script>

{#await actions then items}
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
  <div>nazwa</div>
{/await}
